// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwAQRwYn7zXXN5R8iXGfS_LLxKi-QQFeM',
    appId: '1:113222246651:web:10189f5016268a5a0b505e',
    messagingSenderId: '113222246651',
    projectId: 'tiffinhub-app',
    authDomain: 'tiffinhub-app.firebaseapp.com',
    storageBucket: 'tiffinhub-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB93mSvmG639MK2OzNZms9n2nEHGAYDJ00',
    appId: '1:113222246651:android:795969bd469afeaf0b505e',
    messagingSenderId: '113222246651',
    projectId: 'tiffinhub-app',
    storageBucket: 'tiffinhub-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB03WKlAFmhqNBtCt_UaC43ENPZ9eY9PTA',
    appId: '1:113222246651:ios:0d8c6c22c0acf3370b505e',
    messagingSenderId: '113222246651',
    projectId: 'tiffinhub-app',
    storageBucket: 'tiffinhub-app.firebasestorage.app',
    iosBundleId: 'com.example.tiffinhub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB03WKlAFmhqNBtCt_UaC43ENPZ9eY9PTA',
    appId: '1:113222246651:ios:0d8c6c22c0acf3370b505e',
    messagingSenderId: '113222246651',
    projectId: 'tiffinhub-app',
    storageBucket: 'tiffinhub-app.firebasestorage.app',
    iosBundleId: 'com.example.tiffinhub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwAQRwYn7zXXN5R8iXGfS_LLxKi-QQFeM',
    appId: '1:113222246651:web:640a4f9643635a180b505e',
    messagingSenderId: '113222246651',
    projectId: 'tiffinhub-app',
    authDomain: 'tiffinhub-app.firebaseapp.com',
    storageBucket: 'tiffinhub-app.firebasestorage.app',
  );
}
